// Generated by CoffeeScript 1.7.1
(function() {
  var Collectible, css, u;

  css = "#collect-wrap {\n  position: static;\n}\n#collect-wrap .image-candidate {\n  position: absolute;\n  z-index: 0;\n  cursor: pointer;\n  border: 3px solid gray;\n}\n#collect-wrap .image-candidate:hover {\n  border: 3px solid black;\n}";

  u = {
    addClass: function(el, name) {
      return el.className += el.className.length ? " " + name : name;
    },
    removeClass: function(el, name) {
      return el.className = el.className.replace(new RegExp("\\s*" + name + "\\s*", 'g'), '');
    },
    on: function(el, eventName, callback) {
      return el.addEventListener(eventName, callback);
    },
    off: function(el, eventName, callback) {
      return el.removeEventListener(eventName, callback);
    },
    getOffset: function(el) {
      var left, top;
      left = 0;
      top = 0;
      while (el && el !== document.body) {
        if (isNaN(el.offsetLeft) || isNaN(el.offsetTop)) {
          continue;
        }
        left += el.offsetLeft - el.scrollLeft + el.clientLeft;
        top += el.offsetTop - el.scrollTop + el.clientTop;
        el = el.offsetParent;
      }
      return {
        left: left,
        top: top
      };
    }
  };

  Collectible = (function() {
    function Collectible() {
      this.addCSS();
      this.makeContainer();
      this.highlightImages();
    }

    Collectible.prototype.addCSS = function() {
      var styleElement, styleSheet;
      styleElement = document.createElement('style');
      document.getElementsByTagName('head')[0].appendChild(styleElement);
      styleSheet = document.createTextNode(css);
      return styleElement.appendChild(styleSheet);
    };

    Collectible.prototype.makeContainer = function() {
      this.containerEl = document.createElement('div');
      this.containerEl.id = 'collect-wrap';
      return document.getElementsByTagName('body')[0].appendChild(this.containerEl);
    };

    Collectible.prototype.highlightImages = function() {
      var image, _i, _len, _ref, _results;
      _ref = document.querySelectorAll('img');
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        image = _ref[_i];
        if (image.offsetWidth > 100 && image.offsetHeight > 100) {
          _results.push(this.makeCollectible(image));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    Collectible.prototype.makeCollectible = function(image) {
      var left, overlay, top, _ref;
      overlay = document.createElement('div');
      u.addClass(overlay, 'image-candidate');
      _ref = u.getOffset(image), left = _ref.left, top = _ref.top;
      overlay.style.left = "" + left + "px";
      overlay.style.top = "" + top + "px";
      overlay.style.width = "" + image.offsetWidth + "px";
      overlay.style.height = "" + image.offsetHeight + "px";
      u.on(overlay, 'click', function(e) {
        return (function(image) {
          return console.log('click', image);
        })(image);
      });
      return this.containerEl.appendChild(overlay);
    };

    Collectible.prototype.getPrice = function() {
      return console.log('getting price');
    };

    return Collectible;

  })();

  new Collectible;

}).call(this);
